// AUTO-GENERATED by scripts/generate-fixtures.mjs. Do not edit by hand.
// Reproducible: seeded RNG + fixed reference date (2026-07-03). Re-run the
// generator to regenerate. Realistic Indonesian second-hand phone data in IDR.
import type { ModelSummary } from '@/types';

export const MODELS: ModelSummary[] = [
  {
    "id": "iphone-11",
    "name": "iPhone 11",
    "brand": "Apple",
    "availableStorageGb": [
      64,
      128,
      256
    ]
  },
  {
    "id": "iphone-12",
    "name": "iPhone 12",
    "brand": "Apple",
    "availableStorageGb": [
      64,
      128,
      256
    ]
  },
  {
    "id": "iphone-13",
    "name": "iPhone 13",
    "brand": "Apple",
    "availableStorageGb": [
      128,
      256,
      512
    ]
  },
  {
    "id": "iphone-14",
    "name": "iPhone 14",
    "brand": "Apple",
    "availableStorageGb": [
      128,
      256,
      512
    ]
  },
  {
    "id": "iphone-15",
    "name": "iPhone 15",
    "brand": "Apple",
    "availableStorageGb": [
      128,
      256,
      512
    ]
  },
  {
    "id": "samsung-galaxy-s23",
    "name": "Galaxy S23",
    "brand": "Samsung",
    "availableStorageGb": [
      128,
      256,
      512
    ]
  },
  {
    "id": "samsung-galaxy-a54",
    "name": "Galaxy A54 5G",
    "brand": "Samsung",
    "availableStorageGb": [
      128,
      256
    ]
  },
  {
    "id": "samsung-galaxy-a35",
    "name": "Galaxy A35 5G",
    "brand": "Samsung",
    "availableStorageGb": [
      128,
      256
    ]
  },
  {
    "id": "xiaomi-redmi-note-13",
    "name": "Redmi Note 13",
    "brand": "Xiaomi",
    "availableStorageGb": [
      128,
      256
    ]
  },
  {
    "id": "poco-x6-pro",
    "name": "POCO X6 Pro",
    "brand": "POCO",
    "availableStorageGb": [
      256,
      512
    ]
  },
  {
    "id": "google-pixel-7",
    "name": "Pixel 7",
    "brand": "Google",
    "availableStorageGb": [
      128,
      256
    ]
  },
  {
    "id": "oppo-reno-11",
    "name": "Reno 11 5G",
    "brand": "OPPO",
    "availableStorageGb": [
      256
    ]
  },
  {
    "id": "vivo-v29",
    "name": "V29 5G",
    "brand": "vivo",
    "availableStorageGb": [
      256
    ]
  },
  {
    "id": "iphone-x",
    "name": "iPhone X",
    "brand": "Apple",
    "availableStorageGb": [
      64,
      256
    ]
  },
  {
    "id": "iphone-xr",
    "name": "iPhone XR",
    "brand": "Apple",
    "availableStorageGb": [
      64,
      128,
      256
    ]
  },
  {
    "id": "iphone-se-2022",
    "name": "iPhone SE (2022)",
    "brand": "Apple",
    "availableStorageGb": [
      64,
      128,
      256
    ]
  },
  {
    "id": "iphone-13-pro",
    "name": "iPhone 13 Pro",
    "brand": "Apple",
    "availableStorageGb": [
      128,
      256,
      512
    ]
  },
  {
    "id": "iphone-14-pro",
    "name": "iPhone 14 Pro",
    "brand": "Apple",
    "availableStorageGb": [
      128,
      256,
      512
    ]
  },
  {
    "id": "iphone-15-pro",
    "name": "iPhone 15 Pro",
    "brand": "Apple",
    "availableStorageGb": [
      128,
      256,
      512
    ]
  },
  {
    "id": "iphone-16",
    "name": "iPhone 16",
    "brand": "Apple",
    "availableStorageGb": [
      128,
      256,
      512
    ]
  },
  {
    "id": "iphone-16-plus",
    "name": "iPhone 16 Plus",
    "brand": "Apple",
    "availableStorageGb": [
      128,
      256,
      512
    ]
  },
  {
    "id": "iphone-16e",
    "name": "iPhone 16e",
    "brand": "Apple",
    "availableStorageGb": [
      128,
      256
    ]
  },
  {
    "id": "iphone-16-pro",
    "name": "iPhone 16 Pro",
    "brand": "Apple",
    "availableStorageGb": [
      128,
      256,
      512,
      1024
    ]
  },
  {
    "id": "iphone-16-pro-max",
    "name": "iPhone 16 Pro Max",
    "brand": "Apple",
    "availableStorageGb": [
      256,
      512,
      1024
    ]
  },
  {
    "id": "iphone-17",
    "name": "iPhone 17",
    "brand": "Apple",
    "availableStorageGb": [
      256,
      512
    ]
  },
  {
    "id": "iphone-17-plus",
    "name": "iPhone 17 Plus",
    "brand": "Apple",
    "availableStorageGb": [
      256,
      512
    ]
  },
  {
    "id": "iphone-17-pro",
    "name": "iPhone 17 Pro",
    "brand": "Apple",
    "availableStorageGb": [
      256,
      512,
      1024
    ]
  },
  {
    "id": "iphone-17-pro-max",
    "name": "iPhone 17 Pro Max",
    "brand": "Apple",
    "availableStorageGb": [
      256,
      512,
      1024
    ]
  },
  {
    "id": "samsung-galaxy-s22",
    "name": "Galaxy S22",
    "brand": "Samsung",
    "availableStorageGb": [
      128,
      256
    ]
  },
  {
    "id": "samsung-galaxy-s24",
    "name": "Galaxy S24",
    "brand": "Samsung",
    "availableStorageGb": [
      256,
      512
    ]
  },
  {
    "id": "samsung-galaxy-s24-ultra",
    "name": "Galaxy S24 Ultra",
    "brand": "Samsung",
    "availableStorageGb": [
      256,
      512,
      1024
    ]
  },
  {
    "id": "samsung-galaxy-a34",
    "name": "Galaxy A34 5G",
    "brand": "Samsung",
    "availableStorageGb": [
      128,
      256
    ]
  },
  {
    "id": "samsung-galaxy-a15",
    "name": "Galaxy A15",
    "brand": "Samsung",
    "availableStorageGb": [
      128,
      256
    ]
  },
  {
    "id": "samsung-galaxy-m14",
    "name": "Galaxy M14 5G",
    "brand": "Samsung",
    "availableStorageGb": [
      128
    ]
  },
  {
    "id": "xiaomi-redmi-note-12",
    "name": "Redmi Note 12",
    "brand": "Xiaomi",
    "availableStorageGb": [
      128,
      256
    ]
  },
  {
    "id": "xiaomi-14",
    "name": "Xiaomi 14",
    "brand": "Xiaomi",
    "availableStorageGb": [
      256,
      512
    ]
  },
  {
    "id": "poco-x6",
    "name": "POCO X6",
    "brand": "POCO",
    "availableStorageGb": [
      256,
      512
    ]
  },
  {
    "id": "xiaomi-redmi-13c",
    "name": "Redmi 13C",
    "brand": "Xiaomi",
    "availableStorageGb": [
      128,
      256
    ]
  },
  {
    "id": "oppo-a78",
    "name": "A78 5G",
    "brand": "OPPO",
    "availableStorageGb": [
      128,
      256
    ]
  },
  {
    "id": "oppo-a58",
    "name": "A58",
    "brand": "OPPO",
    "availableStorageGb": [
      128
    ]
  },
  {
    "id": "vivo-v30",
    "name": "V30 5G",
    "brand": "vivo",
    "availableStorageGb": [
      256,
      512
    ]
  },
  {
    "id": "vivo-y36",
    "name": "Y36",
    "brand": "vivo",
    "availableStorageGb": [
      128,
      256
    ]
  },
  {
    "id": "realme-12",
    "name": "Realme 12",
    "brand": "Realme",
    "availableStorageGb": [
      128,
      256
    ]
  },
  {
    "id": "realme-c55",
    "name": "Realme C55",
    "brand": "Realme",
    "availableStorageGb": [
      128,
      256
    ]
  },
  {
    "id": "realme-11",
    "name": "Realme 11",
    "brand": "Realme",
    "availableStorageGb": [
      128,
      256
    ]
  },
  {
    "id": "infinix-note-40",
    "name": "Infinix Note 40",
    "brand": "Infinix",
    "availableStorageGb": [
      128,
      256
    ]
  },
  {
    "id": "tecno-spark-20",
    "name": "Tecno Spark 20",
    "brand": "Tecno",
    "availableStorageGb": [
      128,
      256
    ]
  }
];

/** Model ids to surface in the "trending" row, most popular first. */
export const TRENDING_MODEL_IDS: string[] = [
  "iphone-16",
  "samsung-galaxy-a54",
  "xiaomi-redmi-note-13",
  "realme-12",
  "iphone-15",
  "poco-x6",
  "samsung-galaxy-s24",
  "oppo-reno-11",
  "iphone-17-pro-max",
  "vivo-v30",
  "samsung-galaxy-a15",
  "infinix-note-40",
  "iphone-14",
  "tecno-spark-20"
];

const BY_ID: Record<string, ModelSummary> = Object.fromEntries(
  MODELS.map((m) => [m.id, m]),
);

export function getModel(id: string): ModelSummary | undefined {
  return BY_ID[id];
}
