// AUTO-GENERATED by scratchpad/gen-fixtures.mjs. Do not edit by hand.
// Reproducible: seeded RNG + fixed reference date (2026-07-03). Re-run the
// generator to regenerate. Realistic Indonesian second-hand phone data in IDR.
import type { ModelSummary } from '@/types';

export const MODELS: ModelSummary[] = [
  {
    "id": "iphone-11",
    "name": "iPhone 11",
    "brand": "Apple",
    "availableStorageGb": [
      64,
      128,
      256
    ]
  },
  {
    "id": "iphone-12",
    "name": "iPhone 12",
    "brand": "Apple",
    "availableStorageGb": [
      64,
      128,
      256
    ]
  },
  {
    "id": "iphone-13",
    "name": "iPhone 13",
    "brand": "Apple",
    "availableStorageGb": [
      128,
      256,
      512
    ]
  },
  {
    "id": "iphone-14",
    "name": "iPhone 14",
    "brand": "Apple",
    "availableStorageGb": [
      128,
      256,
      512
    ]
  },
  {
    "id": "iphone-15",
    "name": "iPhone 15",
    "brand": "Apple",
    "availableStorageGb": [
      128,
      256,
      512
    ]
  },
  {
    "id": "samsung-galaxy-s23",
    "name": "Galaxy S23",
    "brand": "Samsung",
    "availableStorageGb": [
      128,
      256,
      512
    ]
  },
  {
    "id": "samsung-galaxy-a54",
    "name": "Galaxy A54 5G",
    "brand": "Samsung",
    "availableStorageGb": [
      128,
      256
    ]
  },
  {
    "id": "samsung-galaxy-a35",
    "name": "Galaxy A35 5G",
    "brand": "Samsung",
    "availableStorageGb": [
      128,
      256
    ]
  },
  {
    "id": "xiaomi-redmi-note-13",
    "name": "Redmi Note 13",
    "brand": "Xiaomi",
    "availableStorageGb": [
      128,
      256
    ]
  },
  {
    "id": "poco-x6-pro",
    "name": "POCO X6 Pro",
    "brand": "POCO",
    "availableStorageGb": [
      256,
      512
    ]
  },
  {
    "id": "google-pixel-7",
    "name": "Pixel 7",
    "brand": "Google",
    "availableStorageGb": [
      128,
      256
    ]
  },
  {
    "id": "oppo-reno-11",
    "name": "Reno 11 5G",
    "brand": "OPPO",
    "availableStorageGb": [
      256
    ]
  },
  {
    "id": "vivo-v29",
    "name": "V29 5G",
    "brand": "vivo",
    "availableStorageGb": [
      256
    ]
  }
];

/** Model ids to surface in the "trending" row, most popular first. */
export const TRENDING_MODEL_IDS: string[] = [
  "iphone-11",
  "iphone-13",
  "iphone-14",
  "iphone-12",
  "iphone-15",
  "samsung-galaxy-s23"
];

const BY_ID: Record<string, ModelSummary> = Object.fromEntries(
  MODELS.map((m) => [m.id, m]),
);

export function getModel(id: string): ModelSummary | undefined {
  return BY_ID[id];
}
